### PR TITLE
Pagination block

### PR DESCRIPTION
**Pull request by sergeiten**
Display pagination block if there are more than one page.

### CODE REVIEW

**Comment by ForPeople** [comment]
Hmm... I don't think so.
Even if  '$page_navigation->total_page == 1' is true, Board's pagination should display page's no. '1'.

**Comment by sergeiten** [comment]
Hello,

I think it's illogical to display pagination menu if there is only one page.

I am sure purpose of pagination links to have ability is switching between
pages, but why we need to display "First Page" and "Last Page" links if
they go to the same page I am on now.

If the purpose of pagination block is displaying page number in case if
only one page - this I think illogical too, because if there is no any
other pages so it means I am on first page.

On Wed, Jan 8, 2014 at 4:39 PM, 푸시아 notifications@github.com wrote:

> Hmm... I don't think so.
> Even if '$page_navigation->total_page == 1' is true, Board's pagination
> should display page's no. '1'.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/xpressengine/xe-module-board/pull/23#issuecomment-31811128
> .

## 

Kind Regards,

Sergei Ten

Mobile: +82 010 2015-8486
Skype: serg.ten

**Comment by ForPeople** [comment]
Well,
This is just Skin's issue. So, you can make another if you want to fix something.

**Comment by sergeiten** [comment]
Yes, I always do in project based on XE. Just suggested to include fix.

Anyway thank you :)

On Wed, Jan 8, 2014 at 5:21 PM, 푸시아 notifications@github.com wrote:

> Well,
> This is just Skin's issue. So, you can make another if you want to fix
> something.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/xpressengine/xe-module-board/pull/23#issuecomment-31812819
> .

## 

Kind Regards,

Sergei Ten

Mobile: +82 010 2015-8486
Skype: serg.ten

**Pull request closed without merging**
